/**
 * Export the whole database (schema + data) to a single portable .sql file.
 *
 *   npm run export:sql                 -> writes ../neo_automation.sql (repo root)
 *   npm run export:sql -- path/to.sql  -> writes to a custom path
 *
 * The output is deliberately MariaDB- AND MySQL-compatible:
 *  - schema comes from src/schema.ts (utf8mb4 / utf8mb4_unicode_ci, plain types),
 *    NOT from `mysqldump`, which injects MySQL-8-only `/*!80016 …*​/` clauses that
 *    break a phpMyAdmin/MariaDB import on typical cPanel hosts.
 *  - every value is escaped by hand, and JSON columns are stringified, so the
 *    file imports cleanly on MySQL 5.7+/8.0 and MariaDB 10.x alike.
 *
 * Import it into an EMPTY database (phpMyAdmin › Import, or `mysql db < file`).
 */
import dotenv from "dotenv";
dotenv.config();

import fs from "fs";
import path from "path";
import { TABLES } from "./schema";
import { ensureDatabase, getPool, query } from "./db";

// Logical dump order (no foreign keys, so any order imports — this is just tidy).
const ORDER = ["admins", "brands", "categories", "industries", "products", "inquiries"];

/** The CREATE statement for a table, turned into a drop-and-recreate with an
 *  explicit, portable charset/collation. */
function ddlFor(table: string): string {
  const raw = TABLES.find((t) =>
    new RegExp(`CREATE TABLE IF NOT EXISTS ${table}\\b`).test(t)
  );
  if (!raw) throw new Error(`No DDL found in schema.ts for table "${table}"`);
  return raw
    .replace("CREATE TABLE IF NOT EXISTS", "CREATE TABLE")
    .replace(
      /ENGINE=InnoDB/,
      "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    );
}

/** Render a JS value as a SQL literal. Objects/arrays (JSON columns) are
 *  stringified; strings are escaped for a single-quoted MySQL/MariaDB literal. */
const ESC: Record<string, string> = {
  "\0": "\\0",
  "\b": "\\b",
  "\t": "\\t",
  "\n": "\\n",
  "\r": "\\r",
  "\x1a": "\\Z",
  "'": "\\'",
  "\\": "\\\\",
};
function sqlValue(v: any): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (Buffer.isBuffer(v)) v = v.toString("utf8");
  const s = typeof v === "object" ? JSON.stringify(v) : String(v);
  return "'" + s.replace(/[\0\b\t\n\r\x1a'\\]/g, (c) => ESC[c]) + "'";
}

async function main() {
  const dest = process.argv[2]
    ? path.resolve(process.argv[2])
    : path.resolve(__dirname, "../../neo_automation.sql");

  await ensureDatabase(); // verify we can connect / the DB exists

  const out: string[] = [];
  out.push("-- Neo Automation — full database export (schema + data)");
  out.push("-- Generated by `npm run export:sql`. Import into an EMPTY database:");
  out.push("--   phpMyAdmin › Import,  or  `mysql -u USER -p DBNAME < neo_automation.sql`");
  out.push("-- Compatible with MySQL 5.7+/8.0 and MariaDB 10.x (utf8mb4_unicode_ci).");
  out.push("");
  out.push('SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";');
  out.push("SET FOREIGN_KEY_CHECKS = 0;");
  out.push("SET NAMES utf8mb4;");
  out.push("");

  const counts: Record<string, number> = {};
  for (const table of ORDER) {
    out.push("-- ---------------------------------------------------------------");
    out.push(`-- Table structure & data for \`${table}\``);
    out.push("-- ---------------------------------------------------------------");
    out.push(`DROP TABLE IF EXISTS \`${table}\`;`);
    out.push(ddlFor(table) + ";");
    out.push("");

    const rows = await query<Record<string, any>>(`SELECT * FROM \`${table}\``);
    counts[table] = rows.length;
    if (rows.length) {
      const cols = Object.keys(rows[0]);
      const colList = cols.map((c) => `\`${c}\``).join(", ");
      out.push(`-- ${rows.length} row(s)`);
      for (const r of rows) {
        const vals = cols.map((c) => sqlValue(r[c])).join(", ");
        out.push(`INSERT INTO \`${table}\` (${colList}) VALUES (${vals});`);
      }
    } else {
      out.push("-- (no rows)");
    }
    out.push("");
  }

  out.push("SET FOREIGN_KEY_CHECKS = 1;");
  out.push("");

  fs.writeFileSync(dest, out.join("\n"), "utf8");
  await getPool().end();

  const summary = ORDER.map((t) => `${t}=${counts[t]}`).join("  ");
  console.log(`✓ Wrote ${dest}`);
  console.log(`  rows: ${summary}`);
}

main().catch((e) => {
  console.error("Export failed:", e);
  process.exit(1);
});
