/**
 * Initial content, mirroring the frontend src/data/* seed files. Inserted on
 * first boot only (when a table is empty), so editing data later via the admin
 * panel is never overwritten. Keep ids in sync with the frontend if you re-seed.
 */

const p = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1000&q=80`;
const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;
const logo = (id: string) => `/images/brands/${id}.png`;

export const seedBrands = [
  { id: "atlas-copco", name: "Atlas Copco", color: "#0033A0", category: "Assembly & Tightening", blurb: "Industrial power tools, smart tightening systems and the Smart Workflow Feature (SWF) for error-proof assembly lines.", logo: logo("atlas-copco") },
  { id: "gesipa", name: "GESIPA", color: "#0a4ea2", category: "Riveting Technology", blurb: "Blind rivets, blind rivet nuts and battery-powered setting tools engineered in Germany for high-volume joining.", logo: logo("gesipa") },
  { id: "eepos", name: "eepos", color: "#1b9bd7", category: "Crane Systems", blurb: "Modular aluminium crane systems and ergonomic lifting solutions for flexible, lightweight material handling.", logo: logo("eepos") },
  { id: "gedore", name: "GEDORE", color: "#0b63b2", category: "Hand Tools", blurb: "Premium hand tools, torque wrenches and workshop trolleys trusted across global manufacturing floors.", logo: logo("gedore") },
  { id: "cejn", name: "CEJN", color: "#ee7203", category: "Pneumatics & Connectors", blurb: "Swedish-engineered quick-connect couplings, high-pressure connectors and safety air guns for fast, leak-free pneumatic and hydraulic connections.", logo: logo("cejn") },
  { id: "hoffmann-group", name: "Hoffmann Group", color: "#ff7300", category: "Tooling & MRO", blurb: "Europe's system partner for quality tools — GARANT and HOLEX precision tools, measuring equipment and workstation solutions for industrial MRO.", logo: logo("hoffmann-group") },
  { id: "legris", name: "Legris", color: "#0a3d91", category: "Fluid & Pneumatic Fittings", blurb: "Precision push-in fittings, connectors and tubing engineered in France for reliable compressed-air and fluid control.", logo: logo("legris") },
  { id: "pferd", name: "PFERD", color: "#1f6fb2", category: "Abrasives & Cutting", blurb: "High-performance cutting discs, grinding wheels and surface finishing tools for metalworking precision.", logo: logo("pferd") },
  { id: "john-guest", name: "John Guest", color: "#0e7ec4", category: "Fluid Fittings", blurb: "Push-fit connectors and pneumatic fittings delivering leak-free fluid and air transfer at scale.", logo: logo("john-guest") },
];

export const seedCategories = [
  { id: "assembly-tools", name: "Assembly & Tightening", description: "Smart cordless and electric tightening systems with traceability.", icon: "Wrench" },
  { id: "riveting-systems", name: "Riveting Systems", description: "Blind rivet & rivet-nut setting tools for structural joining.", icon: "Hammer" },
  { id: "crane-systems", name: "Crane Systems", description: "Modular aluminium cranes and ergonomic lifting solutions.", icon: "MoveVertical" },
  { id: "hand-tools", name: "Hand Tools & Storage", description: "Premium hand tools, torque wrenches and workshop trolleys.", icon: "Wrench" },
  { id: "abrasives-cutting", name: "Abrasives & Cutting", description: "Cutting discs, grinding wheels and surface finishing.", icon: "Disc3" },
  { id: "fluid-fittings", name: "Fluid & Pneumatic Fittings", description: "Push-fit connectors for leak-free fluid and air transfer.", icon: "Pipette" },
];

export const seedIndustries = [
  { id: "automotive", name: "Automotive", short: "Precision at line speed", tagline: "Zero-defect assembly for the mobility era", description: "From body-in-white to final assembly, we deploy smart tightening, riveting and error-proofing systems that keep automotive lines moving at takt time with full traceability.", image: img("1565043666747-69f6646db940"), icon: "Car", accent: "#ed1c24", capabilities: ["Smart tightening & torque traceability", "Structural blind riveting (BIW)", "Ergonomic crane-assisted handling", "Line-side surface finishing"], stat: { value: "40%", label: "faster takt cycles" } },
  { id: "aerospace", name: "Aerospace", short: "Aviation-grade joining", tagline: "Where every fastener is mission-critical", description: "Aerospace assembly demands certified torque, documented processes and flawless surface integrity. Our calibrated tooling and abrasives meet the most exacting AS9100 environments.", image: img("1436491865332-7a61a109cc05"), icon: "Plane", accent: "#22b8ff", capabilities: ["Calibrated precision torque tools", "Composite & alloy finishing", "Documented process control", "Lightweight lifting systems"], stat: { value: "100%", label: "torque traceability" } },
  { id: "data-center", name: "Data Center", short: "Build the backbone of compute", tagline: "Infrastructure assembled to the micron", description: "Hyperscale build-outs need rapid, repeatable rack assembly and clean cable management. We supply pneumatic fittings, precision hand tools and ergonomic handling for 24/7 deployment.", image: img("1558494949-ef010cbdcc31"), icon: "Server", accent: "#5ed6ff", capabilities: ["Push-fit fluid & cooling fittings", "Precision rack assembly tooling", "ESD-safe hand tools", "Rapid material handling"], stat: { value: "24/7", label: "deployment uptime" } },
  { id: "general-industries", name: "General Industries", short: "One partner, every process", tagline: "Tooling the world's workshops", description: "Fabrication, machinery, white goods and beyond — our complete catalogue of assembly, cutting and material-handling solutions powers general manufacturing across the board.", image: img("1565514020179-026b92b84bb6"), icon: "Factory", accent: "#ff5d5d", capabilities: ["Full assembly tool range", "Cutting, grinding & abrasives", "Modular crane systems", "Workshop tooling & storage"], stat: { value: "1200+", label: "installations" } },
  { id: "electronics-ev", name: "Electronics & EV", short: "Powering electrification", tagline: "Micro-precision for high-volume electronics", description: "Battery packs, power electronics and connected devices require delicate, traceable assembly. Our smart tools deliver micro-torque control and ESD-safe handling at scale.", image: img("1518770660439-4636190af475"), icon: "CircuitBoard", accent: "#22b8ff", capabilities: ["Micro-torque smart tools", "Battery module assembly", "ESD-safe environments", "Connector & fitting solutions"], stat: { value: "±2%", label: "torque accuracy" } },
  { id: "energy-utilities", name: "Energy & Utilities", short: "Built to endure", tagline: "Heavy-duty tooling for critical infrastructure", description: "Power generation, transmission and renewables operate in the harshest conditions. Our rugged tooling and lifting systems are engineered for reliability where downtime is not an option.", image: img("1466611653911-95081537e5b7"), icon: "Zap", accent: "#ed1c24", capabilities: ["High-torque bolting systems", "Heavy lifting & cranes", "Field-service tool kits", "Maintenance abrasives"], stat: { value: "99.2%", label: "field reliability" } },
];

export const seedProducts = [
  { id: "ac-tensor-es", slug: "atlas-copco-tensor-es-cordless", name: "Tensor ES Cordless Nutrunner", brandId: "atlas-copco", brand: "Atlas Copco", categoryId: "assembly-tools", industries: ["automotive", "aerospace", "electronics-ev"], price: 489000, rating: 4.9, shortDesc: "Smart cordless tightening tool with full torque & angle traceability.", description: "The Tensor ES delivers transducer-controlled accuracy with real-time torque and angle feedback. Integrated with the Smart Workflow Feature (SWF), every result is documented, traced and error-proofed — the benchmark for critical-joint assembly.", features: ["Transducer-controlled ±2% torque accuracy", "Wireless SWF connectivity & traceability", "Ergonomic, low-reaction grip", "OLED display with live results"], specs: [{ label: "Torque Range", value: "5 – 50 Nm" }, { label: "Speed", value: "Up to 950 rpm" }, { label: "Accuracy", value: "± 2% Cm/Cmk" }, { label: "Connectivity", value: "Wireless / SWF" }, { label: "Weight", value: "1.1 kg" }], images: [p("1581092160562-40aa08e78837"), p("1504328345606-18bbc8c9d7d1")], featured: true, special: true, badge: "SWF Ready", visible: true },
  { id: "ac-power-focus", slug: "atlas-copco-power-focus-6000", name: "Power Focus 6000 Controller", brandId: "atlas-copco", brand: "Atlas Copco", categoryId: "assembly-tools", industries: ["automotive", "general-industries"], price: 612000, rating: 4.8, shortDesc: "Modular tightening controller orchestrating multi-tool assembly stations.", description: "Power Focus 6000 is the brain of the smart assembly line — a scalable controller that manages tightening strategies, traceability and line integration across multiple tools from a single intuitive interface.", features: ["Multi-tool orchestration", "Smart tightening strategies", "Open protocol & PLC integration", "Touch HMI configuration"], specs: [{ label: "Channels", value: "Up to 20 tools" }, { label: "Protocols", value: "Open Protocol, Profinet" }, { label: "Storage", value: "Full result traceability" }, { label: "Display", value: "7\" touchscreen" }], images: [p("1518770660439-4636190af475"), p("1581091226825-a6a2a5aee158")], featured: true, special: true, badge: "Smart Line", visible: true },
  { id: "gesipa-accubird", slug: "gesipa-accubird-pro-rivet-tool", name: "AccuBird Pro Blind Rivet Tool", brandId: "gesipa", brand: "GESIPA", categoryId: "riveting-systems", industries: ["automotive", "aerospace", "general-industries"], price: 78500, rating: 4.7, shortDesc: "Battery-powered blind rivet setting tool with process monitoring.", description: "The AccuBird Pro sets blind rivets up to 4.8 mm in all materials with consistent, monitored force. Lightweight and fast, it brings German riveting precision to high-volume structural joining.", features: ["Sets rivets up to Ø 4.8 mm", "Process & setting-force monitoring", "Brushless motor, 2.5 kN traction", "Quick-change nosepiece system"], specs: [{ label: "Rivet Capacity", value: "Ø 2.4 – 4.8 mm" }, { label: "Traction Force", value: "2.5 kN" }, { label: "Stroke", value: "20 mm" }, { label: "Battery", value: "18V Li-Ion" }, { label: "Weight", value: "2.0 kg" }], images: [p("1530124566582-a618bc2615dc"), p("1572981779307-38b8cabb2407")], featured: true, special: true, badge: "Best Seller", visible: true },
  { id: "gesipa-firebird", slug: "gesipa-firebird-pro-rivet-nut", name: "FireBird Pro Rivet-Nut Setter", brandId: "gesipa", brand: "GESIPA", categoryId: "riveting-systems", industries: ["automotive", "general-industries"], price: 89900, rating: 4.6, shortDesc: "High-speed blind rivet-nut tool for threaded fastening.", description: "FireBird Pro sets blind rivet nuts up to M10 with programmable stroke and force control, ideal for adding strong threads to thin-walled structures.", features: ["Sets rivet nuts up to M10", "Stroke & force programmable", "Fast cycle, low fatigue", "Digital setting feedback"], specs: [{ label: "Capacity", value: "M3 – M10" }, { label: "Setting Force", value: "20 kN" }, { label: "Battery", value: "18V Li-Ion" }, { label: "Weight", value: "2.2 kg" }], images: [p("1572981779307-38b8cabb2407"), p("1530124566582-a618bc2615dc")], visible: true },
  { id: "eepos-alu-crane", slug: "eepos-modular-aluminium-crane", name: "Modular Aluminium Crane System", brandId: "eepos", brand: "eepos", categoryId: "crane-systems", industries: ["automotive", "general-industries", "aerospace"], price: 1450000, rating: 4.8, shortDesc: "Lightweight modular crane for ergonomic, flexible material handling.", description: "The eepos aluminium crane combines low dead weight with high rigidity, enabling effortless one-hand movement of loads. Modular profiles configure to any workstation layout.", features: ["Loads up to 2000 kg", "Ultra-low rolling resistance", "Modular aluminium profiles", "Ergonomic single-hand guiding"], specs: [{ label: "Capacity", value: "Up to 2000 kg" }, { label: "Span", value: "Up to 8 m" }, { label: "Material", value: "Aircraft-grade aluminium" }, { label: "Mounting", value: "Free-standing / ceiling" }], images: [p("1565514020179-026b92b84bb6"), p("1504917595217-d4dc5ebe6122")], featured: true, special: true, badge: "Ergonomic", visible: true },
  { id: "gedore-trolley", slug: "gedore-workster-tool-trolley", name: "WorkSTER Premium Tool Trolley", brandId: "gedore", brand: "GEDORE", categoryId: "hand-tools", industries: ["general-industries", "automotive", "data-center"], price: 124000, rating: 4.7, shortDesc: "7-drawer workshop trolley with full tool complement.", description: "A mobile workshop in steel — the GEDORE WorkSTER trolley offers smooth ball-bearing drawers, central locking and a curated tool set for professional service teams.", features: ["7 ball-bearing drawers", "Central key locking", "Anti-slip worktop", "Optional full tool set"], specs: [{ label: "Drawers", value: "7" }, { label: "Load / Drawer", value: "30 kg" }, { label: "Material", value: "Powder-coated steel" }, { label: "Castors", value: "4× heavy-duty" }], images: [p("1504328345606-18bbc8c9d7d1"), p("1581091226825-a6a2a5aee158")], visible: true },
  { id: "gedore-torque", slug: "gedore-dremaster-torque-wrench", name: "DREMASTER Torque Wrench", brandId: "gedore", brand: "GEDORE", categoryId: "hand-tools", industries: ["aerospace", "automotive", "energy-utilities"], price: 38500, rating: 4.9, shortDesc: "Precision click-type torque wrench, calibration certified.", description: "The DREMASTER delivers ±3% accuracy with a clear mechanical click. Each wrench ships with an individual calibration certificate for documented, audit-ready torque.", features: ["±3% accuracy", "Individual calibration certificate", "Audible & tactile click", "Reversible ratchet head"], specs: [{ label: "Range", value: "20 – 200 Nm" }, { label: "Accuracy", value: "± 3%" }, { label: "Drive", value: "1/2\"" }, { label: "Standard", value: "ISO 6789" }], images: [p("1581091226825-a6a2a5aee158"), p("1504328345606-18bbc8c9d7d1")], visible: true },
  { id: "pferd-cut-disc", slug: "pferd-sg-steelox-cutting-disc", name: "SG STEELOX Cutting Disc", brandId: "pferd", brand: "PFERD", categoryId: "abrasives-cutting", industries: ["general-industries", "automotive", "energy-utilities"], price: 4200, rating: 4.6, shortDesc: "Ultra-thin high-performance cutting disc for steel & stainless.", description: "PFERD SG STEELOX discs cut steel and stainless with minimal burr and maximum life. The 1 mm profile delivers fast, cool, precise cuts with low material loss.", features: ["1 mm ultra-thin profile", "Steel & stainless (INOX)", "Cool, burr-free cutting", "Long service life"], specs: [{ label: "Diameter", value: "125 mm" }, { label: "Thickness", value: "1.0 mm" }, { label: "Max RPM", value: "12,200 rpm" }, { label: "Material", value: "Aluminium oxide" }], images: [p("1530124566582-a618bc2615dc"), p("1565514020179-026b92b84bb6")], badge: "Pack of 25", visible: true },
  { id: "pferd-flap-disc", slug: "pferd-polifan-flap-disc", name: "POLIFAN Flap Disc", brandId: "pferd", brand: "PFERD", categoryId: "abrasives-cutting", industries: ["aerospace", "general-industries"], price: 5600, rating: 4.7, shortDesc: "Zirconia flap disc for aggressive grinding and finishing.", description: "POLIFAN combines high stock removal with a fine finish, letting you grind and finish in a single step on steel, stainless and alloys.", features: ["Zirconia alumina grain", "Grind & finish in one step", "Cool operation", "Consistent performance"], specs: [{ label: "Diameter", value: "115 mm" }, { label: "Grit", value: "Z40 / Z60 / Z80" }, { label: "Max RPM", value: "13,300 rpm" }, { label: "Backing", value: "Fibreglass" }], images: [p("1572981779307-38b8cabb2407"), p("1530124566582-a618bc2615dc")], visible: true },
  { id: "jg-speedfit", slug: "john-guest-speedfit-connector", name: "Speedfit Push-Fit Connector Set", brandId: "john-guest", brand: "John Guest", categoryId: "fluid-fittings", industries: ["data-center", "general-industries"], price: 8900, rating: 4.8, shortDesc: "Tool-free push-fit fittings for leak-free fluid & air lines.", description: "John Guest Speedfit connectors create instant, secure, leak-free joints with a simple push. Ideal for liquid cooling, pneumatics and rapid data-center fluid routing.", features: ["Tool-free push-to-connect", "Leak-free O-ring seal", "Reusable & demountable", "WRAS / NSF approved"], specs: [{ label: "Tube OD", value: "4 – 22 mm" }, { label: "Pressure", value: "Up to 20 bar" }, { label: "Temp", value: "-20 to 65 °C" }, { label: "Material", value: "Acetal copolymer" }], images: [p("1558494949-ef010cbdcc31"), p("1518770660439-4636190af475")], badge: "Liquid Cooling", visible: true },
  { id: "jg-pneumatic", slug: "john-guest-pneumatic-fitting", name: "Pneumatic Push-In Fitting Range", brandId: "john-guest", brand: "John Guest", categoryId: "fluid-fittings", industries: ["general-industries", "automotive"], price: 6500, rating: 4.6, shortDesc: "Compact push-in fittings for compressed-air automation.", description: "A complete range of compact pneumatic fittings engineered for fast assembly and reliable, vibration-resistant air connections on automated equipment.", features: ["Compact footprint", "Vibration resistant", "360° swivel elbows", "Nickel-plated brass thread"], specs: [{ label: "Tube OD", value: "4 – 16 mm" }, { label: "Pressure", value: "Up to 16 bar" }, { label: "Thread", value: "BSPT / NPT" }, { label: "Body", value: "Acetal / brass" }], images: [p("1504917595217-d4dc5ebe6122"), p("1558494949-ef010cbdcc31")], visible: true },
  { id: "ac-srb-focus", slug: "atlas-copco-srb-handheld", name: "SRB Handheld Battery Nutrunner", brandId: "atlas-copco", brand: "Atlas Copco", categoryId: "assembly-tools", industries: ["general-industries", "automotive", "data-center"], price: 215000, rating: 4.7, shortDesc: "Versatile battery nutrunner for medium-torque assembly.", description: "The SRB series brings reliable, repeatable tightening to general assembly with shut-off control, onboard results and effortless battery operation.", features: ["Shut-off torque control", "Onboard result storage", "Brushless motor", "Lightweight balance"], specs: [{ label: "Torque Range", value: "10 – 100 Nm" }, { label: "Speed", value: "Up to 700 rpm" }, { label: "Battery", value: "18V Li-Ion" }, { label: "Weight", value: "1.6 kg" }], images: [p("1581091226825-a6a2a5aee158"), p("1581092160562-40aa08e78837")], badge: "Versatile", visible: true },
];

export const seedInquiries = [
  { id: "seed-1", name: "Rohan Mehta", email: "rohan@tatamotors.example", phone: "+91 98250 11223", address: "Sanand, Gujarat", message: "Interested in Tensor ES cordless nutrunners for our BIW line. Please share a quote for 12 units with SWF integration.", productId: "ac-tensor-es", productName: "Tensor ES Cordless Nutrunner", status: "new", createdAtOffset: 1000 * 60 * 60 * 5 },
  { id: "seed-2", name: "Anita Sharma", email: "anita@hyperscale.example", phone: "+91 99099 44556", address: "Mumbai DC Campus", message: "Need John Guest Speedfit connectors for a liquid-cooling retrofit. Bulk pricing required.", productId: "jg-speedfit", productName: "Speedfit Push-Fit Connector Set", status: "read", createdAtOffset: 1000 * 60 * 60 * 30 },
  { id: "seed-3", name: "Vikram Patel", email: "vikram@aeroworks.example", phone: "+91 90000 77889", message: "Looking for calibrated torque wrenches, AS9100 documentation.", productId: "gedore-torque", productName: "DREMASTER Torque Wrench", status: "responded", createdAtOffset: 1000 * 60 * 60 * 60 },
];
